<?php
/**
 * Api管理模块
 * User: heyiw
 * Date: 2018/3/15
 * Time: 12:52
 */

namespace app\admin\controller;


use app\common\controller\AdminBase;
use app\common\model\Api as ApiModel;
class Api extends AdminBase
{
    private $api_model = null;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->api_model =  new ApiModel();
    }

    /**
     * api列表页面
     */
    public function apiList(){
        return $this->fetch('system/api_list');
    }

    /**
     * 获取API数据列表
     * @param int $page
     * @param int $limit
     * @return \think\response\Json
     */
    public function getListData( $page = 1,$limit = 10){
        $row = ['msg'=>'','code'=>0,'data'=>[]];
        $map = [];
        $apiData = ApiModel::getList( $map,'',$page,$limit );

        foreach ($apiData['data'] as &$item) {
            $item['type'] = $item['type']==0?'GET':'POST';
        }

        $row['data'] = $apiData['data'];
        $row['count'] = $apiData['total'];

        return json($row);
    }

    /**
     * api接口添加页面
     */
    public function add(){
        return $this->fetch('system/api_add');
    }

    /**
     * 添加API接口
     */
    public function addApi(){
        if ($this->request->isPost()) {
            $data = $this->request->param();
            $validate_result = $this->validate($data, 'Api');

            if ($validate_result !== true) {
                $this->error($validate_result);
            } else {
                if ($this->api_model->allowField(true)->save($data)) {
                    $this->success('保存成功');
                } else {
                    $this->error('保存失败');
                }
            }
        }
    }

    public function save()
    {
        if ($this->request->isPost()) {
            $data = $this->request->except('id');
            $id = $this->request->only('id');
            if ($id == '' || empty($id)) {
                $this->error('错误请求');
            }
            $params = [
                $data['field'] => $data['value']
            ];

            if ($this->api_model->allowField(true)->save($params, $id)) {
                $this->success('保存成功');
            } else {
                $this->error('保存失败');
            }

        }
    }
}