<?php
/**
 * 入驻
 * User: heyiw
 * Date: 2018/4/10
 * Time: 18:36
 */

namespace app\admin\controller;


use app\common\controller\AdminBase;
use app\common\model\ShopGroup;
use think\Config;
use think\Db;

class Enter extends AdminBase
{
    protected  $shop_category;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $this->shop_category = new ShopGroup();

    }


    /**
     * 商家入驻列表
     */
    public function shopIndex(){
        $list = Db::name('shop_enter')->order('status desc,enter_time desc')->select()->toArray();

        if( $list ){
            foreach ($list as &$v){
                $v['enter_time'] = date('Y-m-d H:i:s',$v['enter_time']);
                $v['shop_category'] = $this->shop_category->where(['id'=>$v['c_id']])->field('group_name')->find()->toArray()['group_name'];
            }
        }

        return $this->fetch('shop_index',['list'=>$list]);
    }

    /**
     * 商家入驻状态操作
     */
    public function optionStatus(){
        if( $this->request->isPost()){
            $id = $status = $description = '';
            $params = $this->request->param();
            extract($params);
            if($id == ''){
                $this->error('请求错误');
            }
            $row = Db::name('shop_enter')->where(['id'=>$id])->update([
                'description' => $description,
                'status' => $status,
            ]);
            if( $row ){
                $enterData = Db::name('shop_enter')->where(['id'=>$id])->find();
                if($status == 2 ){//审核通过
                    $password = uniqid();
                    //创建用户
                    $admninData = [
                        'username'     => $enterData['user_phone'],
                        'name'          => $enterData['shop_name'],
                        'password'      => md5($password . Config::get('salt')),
                        'mobile'        => $enterData['user_phone'],
                        'create_time'   => time(),
                        'p_id'          => 0,
                    ];
                    $admninRow = Db::name('admin_user')->insertGetId($admninData);
                    Db::name('shop_enter')->where(['id'=>$id])->update([
                        'password' => $password,
                    ]);
                    //添加权限组
                    Db::name('auth_group_access')->insert([
                        'uid'=>$admninRow,
                        'group_id' => 2
                    ]);
                    //创建商铺
                    $shopData = [
                        'id'        => $admninRow,
                        'shop_name' => $enterData['shop_name'],
                        'shop_category' => $enterData['c_id'],
                        'shop_phone' => $enterData['user_phone'],
                        'live_store_address' => $enterData['address'],
                        'shop_status'   => 1,
                    ];
                    Db::name('shop')->insert($shopData);

                    //创建配送信息
                    $expressData = [
                        's_id' => $admninRow,
                        'company_name' => '商家免费配送',
                        'is_enabled' => 1,
                        'is_default' => 1,
                    ];

                    Db::name('express_company')->insert($expressData);

                }
                $this->success('操作成功');
            }else{
                $this->error('操作失败');
            }

        }else{
            $this->error('请求错误');
        }
    }
}