<?php
/**
 * 图片魔方
 * User: heyiw
 * Date: 2018/4/16
 * Time: 22:43
 */

namespace app\admin\controller;


use app\common\controller\AdminBase;
use think\Db;

class PicModels extends AdminBase
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 首页
     * @return mixed
     */
    public function index(){
        $list = Db::name('pic_model')->where(['s_id' => $this->instance_id, 'is_delete' => 0])->select()->toArray();
        return $this->fetch('',['list'=>$list]);
    }

    /**
     * 编辑页面显示
     * @param int $id
     * @return mixed
     */
    public function edit( $id =0 ){
        $list = Db::name('pages')->select()->toArray();

        $info = Db::name('pic_model')->where([
            'id' => $id,
            's_id' => $this->instance_id,
            'is_delete' => 0,
        ])->find();
        $info['data'] = json_decode($info['data'],true);
        return $this->fetch('',['info'=>$info,'list'=>$list]);
    }

    /**
     * 添加页面显示
     * @return mixed
     */
    public function add(){
        $list = Db::name('pages')->select()->toArray();

        return $this->fetch('',['list'=>$list]);
    }

    /**
     * 添加操作
     */
    public function updatePicModel(){
        //初始化变量
        $name = $url = $img = $picList = $id = $showLocation = '';

        $params = $this->request->param();
        extract($params);
        //过滤
        if( empty($name) ){
            $this->error('请填写规则名称');
        }

        //处理规则
        foreach ($url as $k=>$v){
            if( !empty($v)){
                if(empty($img[$k])){
                    $this->error('请填写完整规则,否则删除');
                }
            }

            $picList['pic_list'][] = [
                'pic_url'=>$img[$k],
                'url'=>$v,
            ];
        }
            $data = [
            'name' =>$name,
            'show_location' =>'HOME',
            'data' => json_encode($picList),
            'addtime' => time(),
            's_id' => $this->instance_id
        ];
        if( empty($id) ){
            $row = Db::name('pic_model')->insert($data);
        }else{
            $row = Db::name('pic_model')->where(['id'=>$id])->update($data);
        }

        if($row){
            $this->success('操作成功');
        }else{
            $this->error('操作失败');
        }

    }

    /**
     * 删除
     * @param $id
     */
    public function delete($id){
        $row = Db::name('pic_model')->delete(['id'=>$id]);
        if($row){
            $this->success('删除成功');
        }else{
            $this->error('删除失败');
        }
    }
}